language: go
go: 1.16.3
services: docker

stages:
  - build
  - publish

branches:
  only:
    - main

jobs:
  include:
    # Build dapper
    - stage: build
      script:
        - go build
    # Build and publish docker tags
    - stage: publish
      if: branch == main AND (NOT (type IN (pull_request)))
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        # Build dockerfile
        - make build
        # Push tags
        - make push
