language: go
go: 1.16.3
services: docker

stages:
  - publish

branches:
  only:
    - main

jobs:
  include:
    - stage: publish
      before_script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
      script:
        # Build dockerfile
        - make build
        # Push tags
        - make push
